// <auto-generated />
using System;
using JustCRM.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustCRM.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610094527_InitialNormalizedSchemaMigration")]
    partial class InitialNormalizedSchemaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JustCRM.API.Entities.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.ToTable("CUSTOMERS", (string)null);
                });

            modelBuilder.Entity("JustCRM.API.Entities.CustomerContact", b =>
                {
                    b.Property<long>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ContactId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ContactId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CUSTOMER_CONTACTS", (string)null);
                });

            modelBuilder.Entity("JustCRM.API.Entities.CustomerDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocumentId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CUSTOMER_DOCUMENTS", (string)null);
                });

            modelBuilder.Entity("JustCRM.API.Entities.CustomerEmployment", b =>
                {
                    b.Property<long>("EmploymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmploymentId"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<long>("IndustryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("EmploymentId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("IndustryId");

                    b.ToTable("CUSTOMER_EMPLOYMENT", (string)null);
                });

            modelBuilder.Entity("JustCRM.API.Entities.Industry", b =>
                {
                    b.Property<long>("IndustryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IndustryId"));

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("IndustryId");

                    b.ToTable("INDUSTRIES", (string)null);

                    b.HasData(
                        new
                        {
                            IndustryId = 1L,
                            IndustryName = "Technology",
                            IsActive = true
                        },
                        new
                        {
                            IndustryId = 2L,
                            IndustryName = "Healthcare",
                            IsActive = true
                        },
                        new
                        {
                            IndustryId = 3L,
                            IndustryName = "Finance",
                            IsActive = true
                        },
                        new
                        {
                            IndustryId = 4L,
                            IndustryName = "Education",
                            IsActive = true
                        },
                        new
                        {
                            IndustryId = 5L,
                            IndustryName = "Manufacturing",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("JustCRM.API.Entities.CustomerContact", b =>
                {
                    b.HasOne("JustCRM.API.Entities.Customer", "Customer")
                        .WithOne("CustomerContact")
                        .HasForeignKey("JustCRM.API.Entities.CustomerContact", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JustCRM.API.Entities.CustomerDocument", b =>
                {
                    b.HasOne("JustCRM.API.Entities.Customer", "Customer")
                        .WithMany("CustomerDocuments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JustCRM.API.Entities.CustomerEmployment", b =>
                {
                    b.HasOne("JustCRM.API.Entities.Customer", "Customer")
                        .WithOne("CustomerEmployment")
                        .HasForeignKey("JustCRM.API.Entities.CustomerEmployment", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCRM.API.Entities.Industry", "Industry")
                        .WithMany("CustomerEmployments")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("JustCRM.API.Entities.Customer", b =>
                {
                    b.Navigation("CustomerContact");

                    b.Navigation("CustomerDocuments");

                    b.Navigation("CustomerEmployment");
                });

            modelBuilder.Entity("JustCRM.API.Entities.Industry", b =>
                {
                    b.Navigation("CustomerEmployments");
                });
#pragma warning restore 612, 618
        }
    }
}
